parameters:
  - name: schemaMigration
    displayName: Run SQL Database Migration
    type: boolean
    default: true
  - name: deployApp2
    displayName: Deploy the Web
    type: boolean
    default: true

pr: none
trigger: none

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.24.0
  pipelines:
    - pipeline: build
      source: Build
      trigger:
        branches:
          include:
            - main

extends:
  template: stages/wrapper_cd.yml@templates
  parameters:
    variableGroupPrefix: 'cd'
    environments:
      - name: Dev
      - name: Test
        dependsOn:
          - Dev
      - name: Training
        dependsOn:
          - Test
      - name: Prod
        dependsOn:
          - Training
    globalVariables:
      - template: .azure/pipelines/variables.yml@self
    deploymentStages:
      - name: Stage
        deploymentJobs:
          - name: Stage Web
            condition: ${{ eq(parameters.deployApp2, true) }}
            steps:
              - template: ../steps/azure_web_app_deploy_slot.yml@templates
                parameters:
                  appName: pins-app-casework-portal-web-$(ENVIRONMENT)
                  appResourceGroup: $(resourceGroup)
                  azurecrName: $(azurecrName)
                  repository: casework-portal/web
              - template: ../steps/azure_web_app_verify_git_hash.yml
                parameters:
                  appName: Web
                  appUrl: $(deploySlotOutputs.slotUrl)/health
                  buildCommit: $(resources.pipeline.build.sourceCommit)
                  auth_enabled: 'false'
                  env: $(ENVIRONMENT)
      - name: Deploy
        dependsOn:
          - Stage
        deploymentJobs:
          - name: Deploy Web
            condition: ${{ eq(parameters.deployApp2, true) }}
            steps:
              - template: ../steps/azure_web_app_slot_swap.yml
                parameters:
                  appName: pins-app-casework-portal-web-$(ENVIRONMENT)
                  appResourceGroup: $(resourceGroup)
                  appStagingSlotName: staging
                  appTargetSlotName: production
              - template: ../steps/azure_web_app_verify_git_hash.yml
                parameters:
                  appName: Web
                  appUrl: https://pins-app-casework-portal-web-$(ENVIRONMENT).azurewebsites.net/health
                  buildCommit: $(resources.pipeline.build.sourceCommit)
                  auth_enabled: 'false'
                  env: $(ENVIRONMENT)
